version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: waifuhospital-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=waifuhospital

volumes:
  mongodb_data: