services:
  mongodb:
    image: mongo:latest
    container_name: waifuhospital-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=waifuhospital
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app_network

  backend:
    build: ./backend
    container_name: waifuhospital-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/waifuhospital
      - JWT_SECRET=waifu_hospital_secret_key_12345
      - PORT=5000
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app_network

  ai_service:
    build: ./ai_service
    container_name: waifuhospital-ai-service
    ports:
      - "5001:5001"
    dns:
      - 8.8.8.8 # Google's primary DNS
      - 8.8.4.4 # Google's secondary DNS
    volumes:
      - ./ai_service:/app
      - /app/node_modules
    environment:
      - PORT=5001
    restart: unless-stopped
    networks:
      - app_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build: ./frontend
    container_name: waifuhospital-frontend
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./frontend:/app:delegated
      - frontend_node_modules:/app/node_modules
    depends_on:
      - backend
      - ai_service
    environment:
      - REACT_APP_API_URL=http://localhost:5000
      - REACT_APP_AI_SERVICE_URL=http://localhost:5001
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - DISABLE_ESLINT_PLUGIN=true
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - app_network

volumes:
  mongodb_data:
  frontend_node_modules:

networks:
  app_network:
    driver: bridge
